server {
  listen 80;
  server_name dreamslms.khanhdevopsvn.live;

  location /vue/ {
    proxy_pass http://52.207.220.199:8081/vue/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}

