server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location /vue/ {
  root /usr/share/nginx/html;
  index index.html;
  try_files $uri $uri/ /vue/index.html;
}

}
